remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-target-blank
title: Hebergs Samfällighetsförening
description: En tillfällig hemsida för Hebergs Samfällighetsförening i Vallda.
